'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Link 
            href="/"
            className="inline-flex items-center text-primary-600 hover:text-primary-700 mb-8"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>

          <h1 className="text-4xl font-bold text-gray-900 mb-8">Disclaimer</h1>
          
          <div className="prose prose-lg max-w-none">
            <p className="text-gray-600 mb-6">
              <strong>Last updated:</strong> {new Date().toISOString().split('T')[0]}
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. General Disclaimer</h2>
              <p className="text-gray-600 mb-4">
                The information provided by What If Story Generator ("we," "us," or "our") on our website is for general informational and entertainment purposes only. All information on the site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. AI-Generated Content</h2>
              <p className="text-gray-600 mb-4">
                Stories generated by our AI system are created for entertainment purposes only. We do not guarantee:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>The accuracy or factual correctness of generated content</li>
                <li>The originality of generated stories</li>
                <li>The appropriateness of content for all audiences</li>
                <li>The suitability of content for any specific purpose</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. No Professional Advice</h2>
              <p className="text-gray-600 mb-4">
                The information on this website should not be construed as professional advice. We are not responsible for any decisions made based on the content generated by our service. Always seek professional advice when needed.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. External Links</h2>
              <p className="text-gray-600 mb-4">
                Our website may contain links to external websites that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. User Responsibility</h2>
              <p className="text-gray-600 mb-4">
                Users are responsible for:
              </p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Reviewing and verifying any generated content before use</li>
                <li>Ensuring generated content is appropriate for their intended audience</li>
                <li>Respecting copyright and intellectual property rights</li>
                <li>Using the service in compliance with applicable laws and regulations</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Limitation of Liability</h2>
              <p className="text-gray-600 mb-4">
                In no event shall What If Story Generator be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence, or other tort, arising out of or in connection with the use of the service or the contents of the service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Service Availability</h2>
              <p className="text-gray-600 mb-4">
                We do not guarantee that the service will be available at all times. The service may be temporarily unavailable due to maintenance, technical issues, or other factors beyond our control.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Changes to Disclaimer</h2>
              <p className="text-gray-600 mb-4">
                We reserve the right to modify this disclaimer at any time. Changes will be effective immediately upon posting on the website. Your continued use of the service after any changes constitutes acceptance of the new disclaimer.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Contact Information</h2>
              <p className="text-gray-600 mb-4">
                If you have any questions about this disclaimer, please contact us at:{' '}
                <a href="mailto:amit.work017@outlook.com" className="text-primary-600 hover:text-primary-700">
                  amit.work017@outlook.com
                </a>
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  )
} 